const mongoos=require("mongoose")
const historySchema= new mongoos.Schema({
    storeId:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        required:true
    },
    customerName:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    startTime:{
        type:Date,
        required:true
    },
    endTime:{
        type:Date,
        required:true
    },
    time:{
        type:Number,
        required:true
    },
    booking:{
        type:Number,
        required:true
    },
    meal:{
        type:Number,
        require:true
    },
    discount:{
        type:Number,
        require:true
    },
    netPay:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        required:true
    }
})
module.exports=mongoos.model('History',historySchema )