const mongoos=require("mongoose")
const orderHistorySchema= new mongoos.Schema({
    storeId:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        required:true
    },
    customers:{
        type:Object,
        required:true
    },
    orderItems:{
        type:Object,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    total:{
        type:Number,
        require:true
    },
    discount:{
        type:Number,
        require:true
    },
    netPay:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        required:true
    },
    transactionId:{
        type:String,
        required:false
    },
    credit:{
        type:Number,
        required:false
    }
})
module.exports=mongoos.model('OrderHistory',orderHistorySchema )