const mongoos=require("mongoose")

const storeSchema= new mongoos.Schema({
    storeName:{
        type:String,
        required:true
    },
    contact:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    onboarding:{
        type:Date,
        required:true
    },
    validTill:{
        type:Date,
        required:false
    },
    profileImage:{
        type:String,
        required:false
    },
    transactionCounter:{
        type:Number,
        required:false
    },
    nightStartTime:{
        type:String,
        required:false
    },
    nightEndTime:{
        type:String,
        required:false
    },
    requiredCustomerCount:{
        type:Number,
        required:false
    },
    happyHrsStartTime:{
        type:String,
        required:false
    },
    happyHrsEndTime:{
        type:String,
        required:false
    },
    happyHrsDiscount:{
        type:Number,
        required:false
    },
    isPauseResume:{
        type:Boolean,
        required:false
    },
    isRoundOff:{
        type:Boolean,
        required:false
    },
    isCancel:{
        type:Boolean,
        required:false
    },
    cancelMins:{
        type:Number,
        required:false
    },
    isBillPrint:{
        type:Boolean,
        required:false
    },
    isPrepaidMode:{
        type:Boolean,
        required:false
    },
    isSwitchTable:{
        type:Boolean,
        required:false
    },
    isSelfStart:{
        type:Boolean,
        required:false
    },
    isHoldEnable:{
        type:Boolean,
        required:false
    },
    isPrintEnable:{
        type:Boolean,
        required:false
    },
    isPrintEnableCheckOut:{
        type:Boolean,
        required:false
    },
    isPrintEnableCafe:{
        type:Boolean,
        required:false
    }
})
module.exports=mongoos.model('Store',storeSchema )